version: '3'
services:
  mysqldb:
    image: mysql
    ports:
      - '3306:3306'
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=myCarDb
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    restart: always
    container_name: mysql
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_USER=user
    - POSTGRES_DB=carDb
    restart: always
    container_name: postgres
       

    