name: L1_CD
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure CarWebApp with a docker container
        run:
           az webapp config container set 
           --docker-custom-image-name ${{vars.CARWEB_IMAGE_ACR_PATH}}:${{vars.IMAGE_TAG}}
           --name ${{vars.CARWEB_APPSERVICE_NAME}}
           --resource-group ${{secrets.RESOURCE_GROUP}}
           --docker-registry-server-url ${{vars.DOCKER_REGISTRY_CONTAINER_URL}}
      
      - name: Set ConnectionString CarWebApp for mysql 
        run: 
           az webapp config appsettings set
          -g ${{secrets.RESOURCE_GROUP}}
          -n ${{vars.CARWEB_APPSERVICE_NAME}}
          --settings PostgreSql=${{secrets.CARWEB_CONNECTION_STRING_POSTGRESQL}}
          
      # - name: Configure CarBillingApp with a docker container
      #   run:
      #      az webapp config container set 
      #      --docker-custom-image-name ${{vars.CARBILLING_IMAGE_ACR_PATH}}:${{vars.IMAGE_TAG}}
      #      --name ${{vars.CARBILLING_APPSERVICE_NAME}} 
      #      --resource-group ${{secrets.RESOURCE_GROUP}}
      #      --docker-registry-server-url ${{vars.DOCKER_REGISTRY_CONTAINER_URL}}