name: L1_CD
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure CarWebApp with a docker container
        run:
           az webapp config container set 
           --docker-custom-image-name carwebcontainer.azurecr.io/carwebapp:2.0 
           --name carwebappService 
           --resource-group AVL-Vali-Testing 
           --docker-registry-server-url https://carwebcontainer.azurecr.io
          
      - name: Configure CarBillingApp with a docker container
        run:
           az webapp config container set 
           --docker-custom-image-name carwebcontainer.azurecr.io/carwebapp:2.0 
           --name carwebappService 
           --resource-group AVL-Vali-Testing 
           --docker-registry-server-url https://carwebcontainer.azurecr.io
      
